### ISSUE TITLE
problems with current master -  Cannot read property 'instance' of undefined  / '1' of null

### ISSUE THREAD

**Issue by gijzelaerr** [astromatic/visiomatic#1]
Hi!

While following the installation/usage instructions here

http://www.astromatic.net/software/visiomatic

I get errors while running the current development master (c6cf1a7898ef8dd88e935e20ece6df35dab352b4)

```
visiomatic.js:29 Uncaught TypeError: Cannot read property 'instance' of undefined
visiomatic.js:28 Uncaught TypeError: Cannot read property '1' of null
```

browser is google chrome 40 on OS X

**Comment by slm23** [comment]
Hi Gijs,
Same problem for me with chrome (linux).  The setup I have (large tiff made by stiff and served by iipsrv.fcgi) works with iipmooviewer and direct URI's for one tile at a time.  Did you find any new information.

**Comment by ebertin** [comment]
Hi all,
sorry for not replying earlier, I just have too much on my plate right now. What is the error if you replace visiomatic.js with the unminified version (visiomatic-src.js)?
Thanks!

**Comment by slm23** [comment]
It looks like: (in the chrome javascript console)
Uncaught TypeError: Cannot read property 'instance' of undefined-----visiomatic.js:2783
(anonymous function)-------------------------------------------------visiomatic.js:2783
Uncaught TypeError: undefined is not a function----------------------visiomatic.js:1530
L.Control.Scale.WCS.L.Control.Scale.extend._updatePixels-------------visiomatic.js:1530
L.Control.Scale.WCS.L.Control.Scale.extend._update-------------------visiomatic.js:1457
o.Mixin.Events.fireEvent---------------------------------------------leaflet.js:6  
o.Map.o.Class.extend._resetView--------------------------------------leaflet.js:6
o.Map.include.setView------------------------------------------------leaflet.js:9 
L.TileLayer.IIP.L.TileLayer.extend._addToMap-------------------------visiomatic.js:909
(anonymous function)-------------------------------------------------visiomatic.js:870
o.Mixin.Events.fireEvent---------------------------------------------leaflet.js:6
L.TileLayer.IIP.L.TileLayer.extend._parseMetadata--------------------visiomatic.js:850
httpRequest.onreadystatechange---------------------------------------visiomatic.js:182

**Comment by slm23** [comment]
Maybe clearer to just put the lines in that are flagged:

"Uncaught TypeError: Cannot read property 'instance' of undefined"
2782/3: aimingRectOptions: {color: '#ff7800', weight: 1, clickable: false,
                            renderer: L.Canvas.instance},

"Uncaught TypeError: undefined is not a function"
1530: this._updateScale(scale, pix + ' px', pix / maxPix);

Thanks.  Let me know if I you need any other details of my installation.

**Comment by ebertin** [comment]
Thanks! Is this with Leaflet 0.8? If not, this could explain the issue.

**Comment by slm23** [comment]
I think it is 0.7.3.  I could not build 0.8 and the download did not
populate the dist/ directory.

**Comment by ebertin** [comment]
Sorry to hear that. v0.8 improves significantly over v0.7.3. I wish a stable version was available at this time. You might want to pick up the Leaflet files I compiled a while ago at http://image.iap.fr/demo/Leaflet/dist and see if the problem is still there.

**Comment by slm23** [comment]
I got 0.8 from github and things are better.  (I had trouble because Debian uses nodejs rather than node as the command and part of the build failed due to this.  Had to simlink node->nodejs in /usr/bin.)

I now get coordinates in lower left but no visible image.  Image adjustment sliders are not active.
Error in javascript console is:
visiomatic.js:1019                        Uncaught TypeError: undefined is not a function

and the line is:                this._addTiles(tileBounds);

I'll try your Leaflet files instead.

**Comment by slm23** [comment]
I got them and it works now!  Thanks a million.  So it was the Leaflet code which is understandable since it is not released.
![screenshot - 02102015 - 02 28 46 pm](https://cloud.githubusercontent.com/assets/4307136/6137857/2b3d2a36-b131-11e4-8680-6bc95f94322d.png)

**Comment by ebertin** [comment]
Great! I will need to update my code and fix this _addTiles() things to have it working with the latest version of Leaflet 0.8 though. If you have a fix I will happily merge it :-).
Oh and please remember that if you want to be able to use the CDS features (catalogs, Sesame, etc.) you will have to setup a proxy on your server since they don't offer CORS (at least the last time I checked).

**Comment by gijzelaerr** [comment]
hi! thanks for the help. 

But when I replace the leaflet code with the files from here: http://image.iap.fr/demo/Leaflet/dist

I now get:

```
visiomatic-src.js:605 Uncaught TypeError: Cannot read property '1' of null
```

**Comment by slm23** [comment]
Hi Again,  Your remarks about CDS/sesame went over my head the first time
but I'd like to get that hooked up.  Is there any docs or code I can read
to understand what is needed for a proxy.  I can certainly set that up once
I understand what I'm trying to do.

**Comment by slm23** [comment]
Looks like I just need to get visquery (cdsclient package) mapped under GET /viz-bin/asu-tsv?... URI's.

If that's not the correct approach please clarify.

**Comment by ebertin** [comment]
Note that setting up a proxy to access [Vizier](http://vizier.u-strasbg.fr/) is no longer required as Vizier now supports [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).
